export const playlist = [
	{ title: 'Johnny B. Goode', artist: 'Chuck Berry', year: 1958 },
	{ title: 'Like a Rolling Stone', artist: 'Bob Dylan', year: 1965 },
	{ title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
	{ title: 'Imagine', artist: 'John Lennon', year: 1971 },
	{ title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971 },
	{ title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
	{ title: 'Hotel California', artist: 'Eagles', year: 1976 },
	{ title: 'Hallelujah', artist: 'Leonard Cohen', year: 1984 },
	{ title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
	{ title: 'Purple Haze', artist: 'Jimi Hendrix', year: 1967 },
	{ title: 'Sweet Home Chicago', artist: 'Robert Johnson', year: 1936 },
	{ title: 'Satisfaction', artist: 'The Rolling Stones', year: 1965 },
	{ title: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
	{ title: 'Born to Be Wild', artist: 'Steppenwolf', year: 1968 },
	{ title: 'Good as Hell', artist: 'Lizzo', year: 2016 },
	{ title: 'Dreams', artist: 'Fleetwood Mac', year: 1977 },
	{ title: 'Thriller', artist: 'Michael Jackson', year: 1982 },
	{ title: 'Wonderwall', artist: 'Oasis', year: 1996 },
	{ title: 'Unforgettable', artist: 'Nat King Cole', year: 1951 },
	{ title: 'Singin\' in the Rain', artist: 'Gene Kelly', year: 1952 },
	{ title: 'Rock Around the Clock', artist: 'Bill Haley', year: 1954 },
	{ title: 'Hound Dog', artist: 'Elvis Presley', year: 1956 },
	{ title: 'Jailhouse Rock', artist: 'Elvis Presley', year: 1957 },
	{ title: 'Great Balls of Fire', artist: 'Jerry Lee Lewis', year: 1957 },
	{ title: 'Peggy Sue', artist: 'Buddy Holly', year: 1957 },
	{ title: 'Twist and Shout', artist: 'The Beatles', year: 1963 },
	{ title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1963 },
	{ title: 'Louie Louie', artist: 'The Kingsmen', year: 1963 },
	{ title: 'Help!', artist: 'The Beatles', year: 1965 },
	{ title: 'Sunshine of Your Love', artist: 'Cream', year: 1968 },
	{ title: 'All Right Now', artist: 'Free', year: 1970 },
	{ title: 'Brown Sugar', artist: 'The Rolling Stones', year: 1971 },
	{ title: 'Black Dog', artist: 'Led Zeppelin', year: 1971 },
	{ title: 'Let It Be', artist: 'The Beatles', year: 1970 },
	{ title: 'God Only Knows', artist: 'The Beach Boys', year: 1966 },
	{ title: 'Mr. Brightside', artist: 'The Killers', year: 2003 },
	{ title: 'Take On Me', artist: 'a-ha', year: 1985 },
	{ title: 'Don\'t Stop Believin\'', artist: 'Journey', year: 1981 },
	{ title: 'Billie Jean', artist: 'Michael Jackson', year: 1983 },
	{ title: 'Beat It', artist: 'Michael Jackson', year: 1982 },
	{ title: 'Like a Virgin', artist: 'Madonna', year: 1984 },
	{ title: 'Wannabe', artist: 'Spice Girls', year: 1996 },
	{ title: 'No Scrubs', artist: 'TLC', year: 1999 },
	{ title: 'Bitter Sweet Symphony', artist: 'The Verve', year: 1997 },
	{ title: 'Zombie', artist: 'The Cranberries', year: 1994 },
	{ title: 'Wonderwall', artist: 'Oasis', year: 1996 },
	{ title: 'Song 2', artist: 'Blur', year: 1997 },
	{ title: 'Creep', artist: 'Radiohead', year: 1992 },
	{ title: 'No Diggity', artist: 'BG & Mystikal', year: 2000 },
	{ title: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2005 },
	{ title: 'Single Ladies', artist: 'Beyoncé', year: 2008 },
	{ title: 'Rolling in the Deep', artist: 'Adele', year: 2010 },
	{ title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', year: 2014 },
	{ title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
	{ title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
	{ title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022 },
	{ title: 'As It Was', artist: 'Harry Styles', year: 2022 },
	{ title: 'Heat Waves', artist: 'Glass Animals', year: 2020 },
	{ title: 'Permission to Dance', artist: 'BTS', year: 2021 },
	{ title: 'Vampire', artist: 'Olivia Rodrigo', year: 2023 },
	{ title: 'Cruel Summer', artist: 'Taylor Swift', year: 2023 },
];